import Container from "./_components/container/Container";
import Footer from "./_components/footer/Footer";
import Header from "./_components/header/Header";
import "./globals.css";
import { Inter } from 'next/font/google'


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Container>
          <Header />
        </Container>
        {children}
        <Footer />
      </body>
    </html >
  );
}
